<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The InteractionPoweR Package • InteractionPoweR</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../../bootstrap-toc.css">
<script src="../../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../../pkgdown.css" rel="stylesheet">
<script src="../../pkgdown.js"></script><meta property="og:title" content="The InteractionPoweR Package">
<meta property="og:description" content="This article describes how to use InteractionPoweR and also explains how the functions underlying this package work.">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../../index.html">InteractionPoweR</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0.4</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../../articles/articles/CommonQuestions.html">Common questions</a>
    </li>
    <li>
      <a href="../../articles/articles/InteractionPoweRvignette.html">The InteractionPoweR Package</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/dbaranger/InteractionPoweR/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="InteractionPoweRvignette_files/header-attrs-2.6/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>The InteractionPoweR Package</h1>
                        <h4 class="author">David AA Baranger</h4>
            
      
      <small class="dont-index">Source: <a href="https://github.com/dbaranger/InteractionPoweR/blob/master/vignettes/articles/InteractionPoweRvignette.Rmd"><code>vignettes/articles/InteractionPoweRvignette.Rmd</code></a></small>
      <div class="hidden name"><code>InteractionPoweRvignette.Rmd</code></div>

    </div>

    
    
<p>The <code>InteractionPoweR</code> package conducts power analyses for regression models in cross-sectional data sets where the term of interest is an interaction between two variables, also known as ‘moderation’ analyses. The package includes functions for simulating data sets, conducting power analyses, and plotting and interpreting results. Notable package features include (1) the ability to compute power for interactions between two continuous variables, (2) effect sizes are all specified as the cross-sectional Pearson’s correlation, (3) simulations do not assume that the interacting variables are independent, (4) any variable in the model, including the outcome, can be binary, and (5) analyses can incorporate the effects of reliability and skew, both of the interacting variables, as well as of the outcome variable.</p>
<div id="introduction" class="section level1">
<h1 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h1>
<p>Interaction analyses take the form:</p>
<p><span class="math display">\[
Y \sim \beta_0 + X_1\beta_1 + X_2\beta_2 + X_1X_2\beta_3 + \epsilon
\]</span></p>
<p>Where <span class="math inline">\(Y\)</span> is the dependent variable, <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are our independent variables, and our interaction term is <span class="math inline">\(X_1X_2\)</span>. The <span class="math inline">\(\beta\)</span>s in this equation are our regression coefficients and <span class="math inline">\(\epsilon\)</span> is our error. Note that in this equation, and throughout the code in this package, we refer to the two interacting variables as <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, as opposed to <span class="math inline">\(X\)</span> and <span class="math inline">\(Z\)</span>, or <span class="math inline">\(X\)</span> and <span class="math inline">\(M\)</span>. This is to emphasize that, as far as these simulations are concerned, <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are interchangeable, and any conclusions about causality (i.e. “moderation”) will rely on the specifics of the variables.</p>
<p>The goal of the power analyses supported by this package is to determine how much power an analysis has to detect whether <span class="math inline">\(\beta_3\)</span> (the interaction term regression coefficient) is different from 0 at some pre-specified <span class="math inline">\(\alpha\)</span> value (<code>alpha</code>, or p-value). <span class="math inline">\(\alpha\)</span> refers to our <em>false positive rate</em>, which is how frequently we will accept that our analysis has incorrectly rejected the null hypothesis. <strong>Power</strong>, refers to our <em>true positive rate</em>, how frequently do we want to correctly accept the alternative hypothesis? It may be easier to think about the inverse of power, the <em>false negative rate</em>: how frequently will we incorrectly accept the null hypothesis? A “typical” (though not necessarily recommended) value for power is 0.8, which means that 20%, or <span class="math inline">\(1/5\)</span>, of the time, the analysis will <em>incorrectly</em> conclude that there is no effect when there actually is one. (We recommend striving for at least a power of .9)</p>
</div>
<div id="effect-sizes" class="section level1">
<h1 class="hasAnchor">
<a href="#effect-sizes" class="anchor"></a>Effect sizes</h1>
<p>Any simulation in this package requires at minimum 5 input variables:</p>
<ol style="list-style-type: decimal">
<li>
<code>N</code>: the sample size.</li>
<li>
<code>r.x1.y</code>: the Pearson’s correlation (<span class="math inline">\(r\)</span>) between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(Y\)</span>
</li>
<li>
<code>r.x2.y</code>: the Pearson’s correlation (<span class="math inline">\(r\)</span>) between <span class="math inline">\(X_2\)</span> and <span class="math inline">\(Y\)</span>
</li>
<li>
<code>r.x1.x2</code>: the Pearson’s correlation (<span class="math inline">\(r\)</span>) between <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>
</li>
<li>
<code>r.x1x2.y</code>: the Pearson’s correlation (<span class="math inline">\(r\)</span>) between <span class="math inline">\(X_1X_2\)</span> and <span class="math inline">\(Y\)</span> - this is the interaction effect</li>
</ol>
<p>It is important to emphasize here that inputs 2-5 are the population-level <em>Pearson’s correlation</em> between each pair of variables. This is true even if any or all of the variables in the simulation are binary. These correlations are used to derive the regression coefficients via path tracing rules. Also note that these effect sizes are the <em>cross-sectional</em> correlation. This is in contrast to how one specifies effects for experimental manipulations, where the effects are the correlation in each of the experimental conditions. The Pearson’s correlation is equivalent to the effect size <span class="math inline">\(\beta\)</span> (i.e. in the regression <span class="math inline">\(Y \sim \beta_0 + X\beta + \epsilon\)</span>) when both <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span> are normalized (mean = 0, sd = 1). For inputs 2-4, we imagine that it will be relatively straightforward for most users to identify the appropriate values (i.e. by surveying the literature and identifying large independent studies where the effects have been reported). However, in the case of the interaction effect size, <code>r.x1x2.y</code>, users may be less used to thinking about interaction effects as correlations. The interaction effect size is the how much the correlation between one of the two independent variables and the dependent variable changes when <em>conditioned</em> on the other independent variable. It is both how much <span class="math inline">\(corr(X_1,Y)\)</span> changes when conditioned on <span class="math inline">\(X_2\)</span>, and equivalently how much <span class="math inline">\(corr(X_2,Y)\)</span> changes when conditioned on <span class="math inline">\(X_1\)</span>.</p>
<p>A common way of thinking about interaction effect sizes is to plot the data as “simple slopes”. A simple slopes plot shows the correlation between one of the independent variables (e.g. <span class="math inline">\(X_1\)</span>) and the dependent variable (<span class="math inline">\(Y\)</span>) in different subsets of the data, where each subset is defined by their value at the second independent variable (e.g. <span class="math inline">\(X_2\)</span>). For example, we can plot <span class="math inline">\(Y \sim X_1\)</span> separately in participants with an <span class="math inline">\(X_2\)</span> value in the lower-half of the distribution and the upper-half of the distribution.</p>
<div id="simulating-single-data-sets" class="section level2">
<h2 class="hasAnchor">
<a href="#simulating-single-data-sets" class="anchor"></a>Simulating single data sets</h2>
<p>To facilitate user’s understanding of interaction effect sizes, <code>InteractionPoweR</code> includes functions for simulating single data sets and plotting the interaction as a simple slopes plot:</p>
<p>The function <code><a href="../../reference/generate_interaction.html">generate_interaction()</a></code> simulates a single data set:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">2020</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/dbaranger/InteractionPoweR">InteractionPoweR</a></span><span class="op">)</span>
<span class="va">example_data</span> <span class="op">=</span> <span class="fu"><a href="../../reference/generate_interaction.html">generate_interaction</a></span><span class="op">(</span>N <span class="op">=</span> <span class="fl">350</span>,        <span class="co"># sample size</span>
                                    r.x1.y <span class="op">=</span> <span class="fl">.2</span>,    <span class="co"># correlation between x1 and y</span>
                                    r.x2.y <span class="op">=</span>  <span class="fl">.1</span>,   <span class="co"># correlation between x2 and y</span>
                                    r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,   <span class="co"># correlation between x1 and x2</span>
                                    r.x1x2.y <span class="op">=</span> <span class="fl">.15</span>  <span class="co"># correlation between x1x2 and y</span>
                                      <span class="op">)</span></code></pre></div>
<p>The data can then be plotted using the <code><a href="../../reference/plot_interaction.html">plot_interaction()</a></code> function:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/plot_interaction.html">plot_interaction</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">example_data</span>, <span class="co"># simulated data</span>
                 q <span class="op">=</span> <span class="fl">2</span>                <span class="co"># number of simple slopes</span>
                 <span class="op">)</span></code></pre></div>
<p><img src="InteractionPoweRvignette_files/figure-html/fig1-1.png" width="576" style="display: block; margin: auto;"></p>
<p>The function <code><a href="../../reference/test_interaction.html">test_interaction()</a></code> provides easy access to the results of the interaction regression, as well as the correlation between the variables, and the slopes of the simple-slopes:</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/test_interaction.html">test_interaction</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">example_data</span>, <span class="co"># simulated data</span>
                 q <span class="op">=</span> <span class="fl">2</span>                <span class="co"># number of simple slopes</span>
                 <span class="op">)</span></code></pre></div>
<pre><code>## $linear.model
##       Estimate Std. Error  t value     Pr(&gt;|t|)
## x1   0.1888967 0.05153863 3.665148 2.859696e-04
## x2   0.1356407 0.05165265 2.626016 9.022851e-03
## x1x2 0.2129386 0.05001033 4.257892 2.661829e-05
## 
## $x1x2.adjusted.r2
## [1] 0.04391331
## 
## $x1x2.confint
##   x1x2_95confint_2.5 x1x2_95confint_97.5
## 1          0.1145761           0.3113011
## 
## $interaction.shape
##   crossover.point    shape
## 1      -0.6369945 1.127275
## 
## $simple.slopes
##    lower.slope upper.slope
## x2  0.00222888   0.3766329
## 
## $correlation
##           cor v1   v2
## 5  0.20000000 x1   x2
## 9  0.22361262 x1    y
## 10 0.18961691 x2    y
## 13 0.03519020 x1 x1x2
## 14 0.07511716 x2 x1x2
## 15 0.23245767  y x1x2</code></pre>
</div>
</div>
<div id="a-simple-power-analysis" class="section level1">
<h1 class="hasAnchor">
<a href="#a-simple-power-analysis" class="anchor"></a>A simple power analysis</h1>
<p>The simplest power analysis we can run is one in which all the parameters are already known. All the correlations are known, the sample size is known, and the interaction effect size is known. The power analysis is run with the function <code><a href="../../reference/power_interaction.html">power_interaction()</a></code>. We additionally specify <code>alpha</code>, which is the p-value we’re using (0.05 is default), and <code>n.iter</code>, which is the number of simulations run. In this example we’ll use just 1,000 simulations, but we recommend using 10,000 for more stable results. Also note that in all these examples the parameter <code>seed</code> is set. This is the seed for the random number generator, which will allow you to obtain the same results. However, we recommend not setting <code>seed</code> when running your own power analyses, at least until you are ready to share the results. Each time an analysis is run a new seed will be chosen and echoed, so that you will be able to reproduce your results.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,  <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,   <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fl">350</span>,        <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,    <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span>  <span class="fl">.1</span>,   <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,   <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fl">.15</span>, <span class="co"># correlation between x1x2 and y</span>
                  seed <span class="op">=</span> <span class="fl">290115</span>  <span class="op">)</span><span class="co"># seed</span></code></pre></div>
<pre><code>## [1] "Checking for errors in inputs..."
## [1] "Performing 1000 simulations"</code></pre>
<pre><code>## # A tibble: 1 x 1
##     pwr
##   &lt;dbl&gt;
## 1 0.824</code></pre>
<p>We find that our analysis has 82% power (<code>pwr</code>).</p>
</div>
<div id="exploring-the-parameter-space" class="section level1">
<h1 class="hasAnchor">
<a href="#exploring-the-parameter-space" class="anchor"></a>Exploring the parameter space</h1>
<p>Typically not all variables are known in a power analysis. For example, we know the magnitude of the interaction effect we’re interested in, and we want to learn what sample size would be needed to detect that effect with 90% power. Or we have a sample already, and we want to learn what is the smallest effect we can detect with 90% power. To answer these questions, the user simply needs to provide the range of parameters that they would like the analysis to use. Almost any of the input parameters can be ranges, and the analysis runs <code>n.iter</code> simulations for every combination of input parameters.</p>
<p>As the number of input parameters increase, so too does the total number of simulations. To reduce the amount of time an analysis takes, <code><a href="../../reference/power_interaction.html">power_interaction()</a></code> supports running simulations in parallel. The number of cores to be used for the parallel simulation is indicated by the <code>cl</code> flag (we recommend a number between 4 - 6 on most personal computers).</p>
<div id="finding-the-optimal-sample-size" class="section level2">
<h2 class="hasAnchor">
<a href="#finding-the-optimal-sample-size" class="anchor"></a>Finding the optimal sample size</h2>
<p>For example, to explore multiple sample sizes we can set <code>N = seq(200,600,by = 50)</code>, which runs a simulation for N = 200, 250, 300 etc, up to N=500. Equivalently, we could also set <code>N  = c(200,250,300,350,400,450,500,550,600)</code>, but the former is faster to write.</p>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span> <span class="op">=</span> <span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,    <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,                  <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">200</span>,<span class="fl">600</span>,by <span class="op">=</span> <span class="fl">50</span><span class="op">)</span>,      <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,                   <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span>  <span class="fl">.1</span>,                  <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,                  <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fl">.15</span>,                <span class="co"># correlation between x1x2 and y</span>
                  cl <span class="op">=</span> <span class="fl">6</span>,                        <span class="co"># number of clusters for parallel analyses</span>
                  seed <span class="op">=</span> <span class="fl">507421</span>        <span class="op">)</span>         <span class="co"># seed</span></code></pre></div>
<pre><code>## [1] "Checking for errors in inputs..."
## [1] "Performing 9000 simulations"</code></pre>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span></code></pre></div>
<pre><code>##     N   pwr
## 1 200 0.564
## 2 250 0.664
## 3 300 0.751
## 4 350 0.827
## 5 400 0.853
## 6 450 0.903
## 7 500 0.921
## 8 550 0.948
## 9 600 0.967</code></pre>
<p>We can plot these results using the function <code><a href="../../reference/plot_power_curve.html">plot_power_curve()</a></code>:</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/plot_power_curve.html">plot_power_curve</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span>, <span class="co"># output from power_interaction()</span>
                 power_target <span class="op">=</span> <span class="fl">.9</span>        <span class="co"># the power we want to achieve </span>
                 <span class="op">)</span></code></pre></div>
<p><img src="InteractionPoweRvignette_files/figure-html/fig2-1.png" width="576" style="display: block; margin: auto;"></p>
<p>By eye-balling this plot, we can see that N=450 yields approximately 90% power, and N=330 yields approximately 80% power. The function <code><a href="../../reference/power_estimate.html">power_estimate()</a></code> can be used to obtain a more precise answer. This function fits a regression model to the power results to estimate when a specific power will be achieved.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/power_estimate.html">power_estimate</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span>, <span class="co"># output from power_interaction()</span>
                        x <span class="op">=</span> <span class="st">"N"</span>,        <span class="co"># the variable we want a precise number for</span>
             power_target <span class="op">=</span> <span class="fl">0.9</span>         <span class="co"># the power we want to achieve </span>
<span class="op">)</span></code></pre></div>
<pre><code>## [1] 442.7771</code></pre>
<p>Our guess turned out to be accurate in this case, and N=443 yields approximately 90% power.</p>
</div>
<div id="finding-the-smallest-detectable-effect-size" class="section level2">
<h2 class="hasAnchor">
<a href="#finding-the-smallest-detectable-effect-size" class="anchor"></a>Finding the smallest detectable effect size</h2>
<p>Another common use-case is when the sample size and variables-of-interest are known, and we want to know how small of an interaction effect can be detected at a certain power level. We can repeat the same steps as above, except this time <code>r.x1x2.y</code> will be a range of values.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span> <span class="op">=</span> <span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,    <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,                  <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fl">350</span>                ,       <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,                   <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span>  <span class="fl">.1</span>,                  <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,                  <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">.1</span>,<span class="fl">.2</span>,by<span class="op">=</span><span class="fl">.01</span><span class="op">)</span>,  <span class="co"># correlation between x1x2 and y</span>
                  cl <span class="op">=</span> <span class="fl">6</span>,                        <span class="co"># number of clusters for parallel analyses</span>
                  seed <span class="op">=</span> <span class="fl">387455</span>        <span class="op">)</span>         <span class="co"># seed</span></code></pre></div>
<pre><code>## [1] "Checking for errors in inputs..."
## [1] "Performing 11000 simulations"</code></pre>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span></code></pre></div>
<pre><code>##    r.x1x2.y   pwr
## 1      0.10 0.501
## 2      0.11 0.543
## 3      0.12 0.603
## 4      0.13 0.704
## 5      0.14 0.763
## 6      0.15 0.809
## 7      0.16 0.828
## 8      0.17 0.905
## 9      0.18 0.918
## 10     0.19 0.942
## 11     0.20 0.965</code></pre>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/plot_power_curve.html">plot_power_curve</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span>, <span class="co"># output from power_interaction()</span>
                 power_target <span class="op">=</span> <span class="fl">.9</span>        <span class="co"># the power we want to achieve </span>
                 <span class="op">)</span></code></pre></div>
<p><img src="InteractionPoweRvignette_files/figure-html/fig3-1.png" width="576" style="display: block; margin: auto;"></p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/power_estimate.html">power_estimate</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span>, <span class="co"># output from power_interaction()</span>
                        x <span class="op">=</span> <span class="st">"r.x1x2.y"</span>,        <span class="co"># the variable we want a precise number for</span>
             power_target <span class="op">=</span> <span class="fl">0.9</span>         <span class="co"># the power we want to achieve </span>
<span class="op">)</span></code></pre></div>
<pre><code>## [1] 0.1738874</code></pre>
<p>We see that we have approximately 90% power to detect effects as small as <code>r.x1x2.y</code> = 0.17.</p>
<p>In some cases it may also be useful to take a look the distribution of simple slopes across the range of parameters tested. If we re-run our simulation using <code>detailed_results=T</code>, we can look at the distribution of effect sizes and simple slopes.</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span> <span class="op">=</span> <span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,    <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,                  <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fl">350</span>                ,       <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,                   <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span>  <span class="fl">.1</span>,                  <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,                  <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">.1</span>,<span class="fl">.2</span>,by<span class="op">=</span><span class="fl">.01</span><span class="op">)</span>,   <span class="co"># correlation between x1x2 and y</span>
                  cl <span class="op">=</span> <span class="fl">6</span>,                         <span class="co"># number of clusters for parallel analyses</span>
                  detailed_results <span class="op">=</span> <span class="cn">T</span>,           <span class="co"># detailed results</span>
                  seed <span class="op">=</span> <span class="fl">316834</span>                  <span class="co"># seed</span>
                <span class="op">)</span></code></pre></div>
<pre><code>## [1] "Checking for errors in inputs..."
## [1] "Performing 11000 simulations"</code></pre>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/plot_simple_slope.html">plot_simple_slope</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span><span class="op">)</span></code></pre></div>
<p><img src="InteractionPoweRvignette_files/figure-html/fig6-1.png" width="576" style="display: block; margin: auto;"></p>
<p>From this we can learn that the range of slopes that would be consistent with the smallest effect we are powered to detect, <code>r.x1x2.y</code>=0.17, is quite large. In particular, note that the lower slope could be negative, 0, or even fairly large in the positive direction - all consistent with <code>r.x1x2.y</code>=0.17. See the section below on <strong>Detailed Results</strong> for more information on all the outputs when <code>detailed.results = TRUE</code>.</p>
</div>
<div id="varying-multiple-parameters" class="section level2">
<h2 class="hasAnchor">
<a href="#varying-multiple-parameters" class="anchor"></a>Varying multiple parameters</h2>
<p>It is not uncommon that multiple parameters in the simulation are unknown. To find the power at every combination of the parameters, simply input a range of values for every unknown parameter in the simulation. We generally recommend to only vary up to 3 parameters at a time, any more and the simulation can take a <em>very</em> long time to run. For example, lets say there’s a range of plausible effect sizes for the interaction, and we want to know how large of a sample we would need to detect each of them. To test this, we can vary both <code>N</code> and <code>r.x1x2.y</code>:</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span> <span class="op">=</span> <span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,     <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,                   <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">100</span>,<span class="fl">600</span>,by <span class="op">=</span> <span class="fl">50</span><span class="op">)</span>,       <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,                    <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span> <span class="fl">.1</span>,                    <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>       ,            <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">.15</span>,<span class="fl">.2</span>,by<span class="op">=</span><span class="fl">.025</span><span class="op">)</span>, <span class="co"># correlation between x1x2 and y</span>
                  cl <span class="op">=</span> <span class="fl">6</span>,                         <span class="co"># number of clusters for parallel analyses</span>
                  detailed_results <span class="op">=</span> <span class="cn">T</span>,
                  seed <span class="op">=</span> <span class="fl">742425</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "Checking for errors in inputs..."
## [1] "Performing 33000 simulations"</code></pre>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/plot_power_curve.html">plot_power_curve</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span>, <span class="co"># output from power_interaction()</span>
                 power_target <span class="op">=</span> <span class="fl">.9</span>,       <span class="co"># the power we want to achieve </span>
                 x <span class="op">=</span> <span class="st">"N"</span>,                 <span class="co"># x-axis</span>
                 group <span class="op">=</span> <span class="st">"r.x1x2.y"</span>       <span class="co"># grouping variable</span>
                 <span class="op">)</span></code></pre></div>
<p><img src="InteractionPoweRvignette_files/figure-html/fig4-1.png" width="576" style="display: block; margin: auto;"></p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/power_estimate.html">power_estimate</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span>, <span class="co"># output from power_interaction()</span>
                        x <span class="op">=</span> <span class="st">"N"</span>,        <span class="co"># the variable we want a precise number for</span>
             power_target <span class="op">=</span> <span class="fl">0.9</span>         <span class="co"># the power we want to achieve </span>
<span class="op">)</span></code></pre></div>
<pre><code>##   r.x1x2.y estimate
## 1    0.150 464.6584
## 2    0.175 322.2866
## 3    0.200 258.9152</code></pre>
<p>From this we’ve learned that, depending on exactly what effect size we’re aiming for, we’ll need an <code>N</code> between 260 and 460.</p>
</div>
</div>
<div id="reliability" class="section level1">
<h1 class="hasAnchor">
<a href="#reliability" class="anchor"></a>Reliability</h1>
<p>Reliability is an important issue in statistics. Even if effects are large, if your measurements are unreliable, then you’ll be under-powered. This is especially true for interactions, as the reliability of both <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> influence power, as well as the reliability of <span class="math inline">\(Y\)</span>. In the context of <code>InteractionPoweR</code>, “reliability” means the proportion of the variance of each variable that is attributable to true signal, as opposed to measurement error. A reliability of ‘1’ (the default), means that your variables were measured with no error (reliability must be greater than 0, and less than or equal to 1). Common statistics that reflect reliability include test-retest reliability, inter-rater reliability, and Cronbach’s alpha. The flags <code>rel.x1</code>, <code>rel.x2</code>, and <code>rel.y</code> control the reliability of each simulated variable. We recommend exploring how much reliability will affect your power. For example:</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span> <span class="op">=</span> <span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,     <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,                   <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fl">450</span>,                        <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,                    <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span> <span class="fl">.1</span>,                    <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,                   <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fl">.15</span>,                 <span class="co"># correlation between x1x2 and y</span>
                  rel.x1 <span class="op">=</span>  <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">.4</span>,<span class="fl">1</span>,by<span class="op">=</span><span class="fl">.2</span><span class="op">)</span>,      <span class="co"># x1 reliability    </span>
                  rel.x2 <span class="op">=</span>  <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">.4</span>,<span class="fl">1</span>,by<span class="op">=</span><span class="fl">.2</span><span class="op">)</span>,      <span class="co"># x2 reliability          </span>
                  rel.y  <span class="op">=</span>  <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">.4</span>,<span class="fl">1</span>,by<span class="op">=</span><span class="fl">.2</span><span class="op">)</span>,      <span class="co"># y reliability          </span>
                  cl <span class="op">=</span> <span class="fl">6</span>,                         <span class="co"># number of clusters for parallel analyses</span>
                  seed <span class="op">=</span> <span class="fl">293437</span>        <span class="op">)</span></code></pre></div>
<pre><code>## [1] "Checking for errors in inputs..."
## [1] "Performing 64000 simulations"</code></pre>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/plot_power_curve.html">plot_power_curve</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span>, <span class="co"># output from power_interaction()</span>
                 power_target <span class="op">=</span> <span class="fl">.9</span>,       <span class="co"># the power we want to achieve </span>
                 x     <span class="op">=</span> <span class="st">"rel.x1"</span>,        <span class="co"># x-axis</span>
                 group <span class="op">=</span> <span class="st">"rel.x2"</span>,        <span class="co"># grouping variable</span>
                 facets<span class="op">=</span> <span class="st">"rel.y"</span>          <span class="co"># facets variable</span>
                 <span class="op">)</span></code></pre></div>
<p><img src="InteractionPoweRvignette_files/figure-html/fig5-1.png" width="576" style="display: block; margin: auto;"></p>
<p>These plots make it clear how large of an effect reliability will have on your results. In this simulation, even a reliability of “acceptable” or “good” (reliability = 0.8), is enough to bring our power down, from 0.9 to 0.63!</p>
</div>
<div id="binary-and-skewed-variables" class="section level1">
<h1 class="hasAnchor">
<a href="#binary-and-skewed-variables" class="anchor"></a>Binary and skewed variables</h1>
<p><code>InteractionPoweR</code> simulates all variables as continuous and normal (skew=0). However, variables can be transformed so that they are binary and/or skewed. Typically, when a continuous and normal variable is transformed to be binary and/or skewed, the correlations between that variable and all other variables are reduced or altered. Sometimes, it makes sense for this to happen in the power analysis. For example, say a variable is continuous in the literature, and the effect sizes in the power analysis are drawn from prior work with the continuous variable, but in your analysis you’ve chosen to dichotomize that variable. In that case, the reduction in correlations makes sense, because that accurately reflects your data analysis and what your power will be. On the other hand, say a variable <em>is</em> binary (at least in the literature), maybe you’re looking at sex or diagnosis for a disorder. Or maybe you are looking at a variable that is skewed in the literature, such as alcohol consumption or depressive symptoms in the general population. In that case, your input correlations are the correlations <em>with the binary/skewed variable</em>, so you don’t want them to be reduced or altered.</p>
<p><code>InteractionPoweR</code> distinguishes between these cases with the <code>adjust.correlations</code> flag. The default is <code>adjust.correlations = TRUE</code>. This indicates that the input correlations are with the binary/skewed variables. To circumvent the problem of variable transformations altering correlations, <code>InteractionPoweR</code> runs a function to compute how much the input correlations need to be adjusted so that the final output variables have the correlation structure specified by the user. When <code>adjust.correlations = FALSE</code>, this function is not run, allowing the user to see the impact of variable transformations on the correlation structure, and on their power.</p>
<p>The flags <code>transform.x1</code>, <code>transform.x2</code>, and <code>transform.y</code> control what distribution <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, and <span class="math inline">\(Y\)</span> are transformed to. Currently, this flag is useful for binarizing, (i.e. dichotomizing) a variable, as in <code>transform.x1 = "binary"</code>. The flags <code>skew.x1</code>, <code>skew.x2</code>, and <code>skew.y</code> control the skew of <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, and <span class="math inline">\(Y\)</span>. We achieve skew by transforming the normally distributed variable to a skewed gamma distribution. We intend to add additional distribution options in future releases. If a <code>skew</code> is specified, the respective <code>transform</code> flag will be automatically set to <code>"gamma"</code>, unless the user specifies <code>"binary"</code>. If a variable is binary, the <code><a href="../../reference/binary.p2skew.html">binary.p2skew()</a></code> convenience function can be used to compute the skew from the proportion of 0’s and 1’s (i.e. 50/50 = 0.5 = a skew of 0). If a variable is binarized but no skew is specified, skew will be set to <code>0</code> by default.</p>
<p>Here’s a single data set where x1, x2, and y are all binary. Note that when <span class="math inline">\(Y\)</span> is binary, the analysis is run as a logistic regression.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Normal</span>
<span class="va">test_data</span> <span class="op">=</span> <span class="fu"><a href="../../reference/generate_interaction.html">generate_interaction</a></span><span class="op">(</span>
                  N <span class="op">=</span> <span class="fl">450</span>,                        <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,                    <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span> <span class="fl">.1</span>,                    <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,                   <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fl">.15</span>,                 <span class="co"># correlation between x1x2 and y</span>
                  transform.x1 <span class="op">=</span> <span class="st">"binary"</span>,        <span class="co"># x1 is binary</span>
                  transform.x2 <span class="op">=</span> <span class="st">"binary"</span>,        <span class="co"># x2 is binary</span>
                  transform.y <span class="op">=</span> <span class="st">"binary"</span>,         <span class="co"># y is binary</span>
                  adjust.correlations <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>     <span class="co"># Adjust correlations for skew?  </span>

<span class="fu"><a href="../../reference/plot_interaction.html">plot_interaction</a></span><span class="op">(</span>data <span class="op">=</span><span class="va">test_data</span> <span class="op">)</span></code></pre></div>
<p><img src="InteractionPoweRvignette_files/figure-html/fig8-1.png" width="576" style="display: block; margin: auto;"></p>
<p>We can also examine the effects on power when the actual variable is skewed:</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span> <span class="op">=</span> <span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,    <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,                   <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fl">450</span>,                        <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,                    <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span> <span class="fl">.1</span>,                    <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,                   <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fl">.15</span>,                 <span class="co"># correlation between x1x2 and y</span>
                  skew.x1 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">2</span>,by<span class="op">=</span><span class="fl">.25</span><span class="op">)</span>,      <span class="co"># x1 skew </span>
                  adjust.correlations <span class="op">=</span> <span class="cn">TRUE</span>,     <span class="co"># Adjust correlations for skew?</span>
                  cl <span class="op">=</span> <span class="fl">6</span> ,                        <span class="co"># number of clusters for parallel analyses</span>
                  seed <span class="op">=</span> <span class="fl">73071</span>      <span class="op">)</span></code></pre></div>
<pre><code>## [1] "Checking for errors in inputs..."
## [1] "Adjusting correlations for variable transformations..."
## [1] "Performing 9000 simulations"</code></pre>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../../reference/plot_power_curve.html">plot_power_curve</a></span><span class="op">(</span>power_data <span class="op">=</span> <span class="va">power_test</span>, <span class="co"># output from power_interaction()</span>
                 power_target <span class="op">=</span> <span class="fl">.9</span>       <span class="co"># the power we want to achieve </span>
                 <span class="op">)</span></code></pre></div>
<p><img src="InteractionPoweRvignette_files/figure-html/fig7-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="detailed-and-full-results" class="section level1">
<h1 class="hasAnchor">
<a href="#detailed-and-full-results" class="anchor"></a>Detailed and full results</h1>
<p>Beyond power and the range of simple slopes, <code>InteractionPoweR</code> generates a lot of additional information about the simulations. These can be optionally returned using <code>detailed_results = TRUE</code> and <code>full_simulation = TRUE</code>. By default, both of these flags are <code>FALSE</code>. <code>detailed_results</code> returns additional information for each unique setting combination, including the mean correlation structure between the simulated variables across <code>niter</code> simulations, and the mean regression coefficients. <code>full_simulation</code>, as the name suggests, returns the output of <code><a href="../../reference/test_interaction.html">test_interaction()</a></code> for every single simulated data set that <code><a href="../../reference/power_interaction.html">power_interaction()</a></code> generates. The output can be quite large (i.e. if 10,000 simulations are run, it will have 10,000 rows).</p>
<div id="detailed-results" class="section level3">
<h3 class="hasAnchor">
<a href="#detailed-results" class="anchor"></a>Detailed results</h3>
<p>Let’s return to our example of examining a range of interaction effect sizes, except now with <code>detailed_results = TRUE</code>. This yields a lot more information about what the simulated data looked like, on average.</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span> <span class="op">=</span> <span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,    <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,                  <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fl">350</span>                ,       <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,                   <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span>  <span class="fl">.1</span>,                  <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,                  <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">.1</span>,<span class="fl">.2</span>,by<span class="op">=</span><span class="fl">.01</span><span class="op">)</span>,  <span class="co"># correlation between x1x2 and y</span>
                  cl <span class="op">=</span> <span class="fl">6</span>,                        <span class="co"># number of clusters for parallel analyses</span>
                  detailed_results <span class="op">=</span> <span class="cn">TRUE</span>        <span class="co"># return detailed results       </span>
                   <span class="op">)</span></code></pre></div>
<pre><code>## [1] "Seed is 277303"
## [1] "Checking for errors in inputs..."
## [1] "Performing 11000 simulations"</code></pre>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span></code></pre></div>
<pre><code>##    r.x1x2.y   pwr x1x2_est_mean x1x2_r2_mean crossover_mean shape_mean
## 1      0.10 0.494     0.1415687   0.01876454     -0.4619808  0.8281285
## 2      0.11 0.534     0.1437299   0.01946217     -0.4524989  0.8487847
## 3      0.12 0.625     0.1488223   0.02126228     -0.4382807  0.8895391
## 4      0.13 0.701     0.1536126   0.02290597     -0.4461747  0.9225177
## 5      0.14 0.768     0.1587378   0.02470927     -0.4051289  0.9234641
## 6      0.15 0.810     0.1637682   0.02631024     -0.3938325  0.9852080
## 7      0.16 0.859     0.1689945   0.02834222     -0.4043839  1.0085705
## 8      0.17 0.895     0.1765999   0.03101163     -0.3789223  1.0596570
## 9      0.18 0.937     0.1840920   0.03388142     -0.3557276  1.0732292
## 10     0.19 0.960     0.1916700   0.03682960     -0.3340812  1.1421984
## 11     0.20 0.975     0.1997528   0.04064131     -0.3387758  1.2221346
##        min.lwr   min.upr   max.lwr   max.upr x1x2_95_CI_2.5_mean
## 1  -0.05729518 0.2122131 0.1732213 0.4303705          0.04055404
## 2  -0.05722042 0.2063897 0.1826742 0.4372992          0.04268456
## 3  -0.06467267 0.2132136 0.1822312 0.4425672          0.04804131
## 4  -0.06854847 0.1982153 0.1937357 0.4528082          0.05304366
## 5  -0.06666062 0.2042873 0.2021232 0.4448863          0.05793824
## 6  -0.08079932 0.1954039 0.1908421 0.4632406          0.06311739
## 7  -0.08371465 0.1969567 0.1943643 0.4569630          0.06843728
## 8  -0.09456866 0.1913897 0.1938572 0.4756132          0.07613918
## 9  -0.10612925 0.1900882 0.2106640 0.4681862          0.08361612
## 10 -0.11340591 0.1818553 0.2047799 0.4896240          0.09110018
## 11 -0.12079139 0.1839233 0.2216293 0.4885893          0.09983078
##    x1x2_95_CI_97.5_mean x1x2_95_CI_width_mean r_y_x1x2_q_2.5 r_y_x1x2_q_50.0
## 1             0.2425833             0.2020293     0.08848426       0.1389968
## 2             0.2447751             0.2020906     0.08806131       0.1388735
## 3             0.2496034             0.2015621     0.09075335       0.1450566
## 4             0.2541815             0.2011378     0.09592175       0.1538546
## 5             0.2595373             0.2015991     0.09636679       0.1560288
## 6             0.2644190             0.2013016     0.09423468       0.1631130
## 7             0.2695517             0.2011144     0.09568028       0.1690827
## 8             0.2770607             0.2009215     0.09855736       0.1796895
## 9             0.2845679             0.2009518     0.11047213       0.1856735
## 10            0.2922399             0.2011397     0.11167161       0.1926035
## 11            0.2996748             0.1998440     0.11473601       0.2034652
##    r_y_x1x2_q_97.5 x1_est_mean x2_est_mean x1_pwr x2_pwr
## 1        0.2291311   0.1881460  0.06275476  0.944  0.221
## 2        0.2310188   0.1856230  0.06133046  0.933  0.224
## 3        0.2298826   0.1887811  0.06184092  0.948  0.205
## 4        0.2437811   0.1891903  0.06458132  0.955  0.228
## 5        0.2528085   0.1892109  0.06101913  0.952  0.227
## 6        0.2609328   0.1878766  0.06147682  0.936  0.217
## 7        0.2635555   0.1853947  0.06471401  0.948  0.231
## 8        0.2708916   0.1856022  0.06270192  0.944  0.227
## 9        0.2844487   0.1869308  0.06226448  0.957  0.218
## 10       0.2908955   0.1871553  0.06077683  0.949  0.214
## 11       0.3005169   0.1867724  0.06399038  0.954  0.223</code></pre>
<p>What is all this?</p>
<p>The first two columns are our standard output, the setting that was varied across simulations, and the power. Next we have <code>x1x2_est_mean</code> and <code>x1x2_r2_mean</code>. This is the <em>mean</em> effect size (<span class="math inline">\(B_3\)</span>) and mean change in the adjusted <span class="math inline">\(R^2\)</span> (or pseudo-<span class="math inline">\(R^2\)</span> when <span class="math inline">\(Y\)</span> is binary) when the interaction term <span class="math inline">\(X_1X_2\)</span> is added to the model. <code>crossover</code> and <code>shape</code> are the value of <span class="math inline">\(X_1\)</span> where the <span class="math inline">\(X_2\)</span> simple slopes intersect, and the shape of the interaction (<span class="math inline">\(B_3 / B_1\)</span>), which reflects whether it is a knock-out, attenuated, or crossover interaction.</p>
<p>Next we have <code>min.lwr</code>, <code>min.upr</code>, <code>max.lwr</code>, and <code>max.upr</code>. These reflect the range of simple-slopes that were observed in the simulations where the interaction was significant. By default, the number of simple slopes (<code>q</code>) is 2 (i.e. a 50/50 split), and <span class="math inline">\(X_2\)</span> is the variable being conditioned on. The ranges reflect that the majority of the lower simple slope ranges from -0.05 to .2, and the upper simple slope ranges from .2 to .45. The proportion of the simple slopes reflected by these ranges can be controlled with the <code>IQR</code> flag. The default value for <code>IQR</code> is 1.5, which means that the output ranges are the median lower and upper simple slope, +/- 1.5 IQRs (an IQR is the 75th percentile - 25th percentile). This output is intended to give further insight into the effect sizes detected by the simulation.</p>
<p><code>x1x2_95_CI_2.5_mean</code> and <code>x1x2_95_CI_97.5_mean</code> are the mean lower and upper 95% confidence intervals of the interaction term, and <code>x1x2_95_CI_width_mean</code> is the mean width of the confidence interval. Similarly, <code>r_y_x1x2_q_2.5</code>, <code>r_y_x1x2_q_50.0</code>, and <code>r_y_x1x2_q_97.5</code> are quantiles (2.5%, 50%, and 97.5%) of the correlation between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X_1X_2\)</span> when the interaction is significant.</p>
<p><code>x1_est_mean</code> and <code>x2_est_mean</code> are the mean main effects of <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span>, and <code>pwr_x1</code> and <code>pwr_x2</code> is the power to detect those main effects, in the context of the full interaction regression.</p>
</div>
<div id="full-results" class="section level3">
<h3 class="hasAnchor">
<a href="#full-results" class="anchor"></a>Full results</h3>
<p><code>full_results</code> can be useful when one wants a better grasp of what goes into the power analysis. If we return to our first example, we can see what range of sample-level correlations one can expect to see, given a population-level correlation:</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">power_test</span> <span class="op">=</span> <span class="fu"><a href="../../reference/power_interaction.html">power_interaction</a></span><span class="op">(</span>n.iter <span class="op">=</span> <span class="fl">1000</span>,  <span class="co"># number of simulations</span>
                  alpha <span class="op">=</span> <span class="fl">0.05</span>,   <span class="co"># p-value</span>
                  N <span class="op">=</span> <span class="fl">350</span>,        <span class="co"># sample size</span>
                  r.x1.y <span class="op">=</span> <span class="fl">.2</span>,    <span class="co"># correlation between x1 and y</span>
                  r.x2.y <span class="op">=</span>  <span class="fl">.1</span>,   <span class="co"># correlation between x2 and y</span>
                  r.x1.x2 <span class="op">=</span> <span class="fl">.2</span>,   <span class="co"># correlation between x1 and x2</span>
                  r.x1x2.y <span class="op">=</span> <span class="fl">.15</span>, <span class="co"># correlation between x1x2 and y</span>
                  full_simulation <span class="op">=</span> <span class="cn">T</span>, <span class="co"># return the full simulation results       </span>
                  seed <span class="op">=</span> <span class="fl">942141</span>
                   <span class="op">)</span></code></pre></div>
<pre><code>## [1] "Checking for errors in inputs..."
## [1] "Performing 1000 simulations"</code></pre>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># the standard output:</span>
<span class="va">power_test</span><span class="op">$</span><span class="va">results</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     pwr
##   &lt;dbl&gt;
## 1 0.812</code></pre>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># range of correlations when the test is significant</span>

<span class="va">quants</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">.025</span>,<span class="fl">.25</span>,<span class="fl">.5</span>,<span class="fl">.75</span>,<span class="fl">.975</span>,<span class="fl">1</span><span class="op">)</span> <span class="co">#quantiles</span>

<span class="va">power_test</span><span class="op">$</span><span class="va">simulation</span> <span class="op">%&gt;%</span> 
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">sig_int</span> <span class="op">==</span><span class="fl">1</span> <span class="op">)</span> <span class="op">%&gt;%</span>  <span class="co"># only significant results</span>
  <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>prob <span class="op">=</span> <span class="va">quants</span>,
                   qs <span class="op">=</span> <span class="fu">stats</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span><span class="op">(</span><span class="va">r_y_x1x2</span>,<span class="va">quants</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##    prob         qs
## 1 0.000 0.05927399
## 2 0.025 0.09522459
## 3 0.250 0.13473967
## 4 0.500 0.16333570
## 5 0.750 0.19638807
## 6 0.975 0.26393664
## 7 1.000 0.34046672</code></pre>
<p>When <span class="math inline">\(B_3\)</span> is significant (<code>sig_int == 1</code>), 95% of the observed sample-level correlations range from 0.1to 0.25, even though the population-level correlation is 0.15! Also note that more than half of the observed <em>significant</em> effect sizes are greater than 0.15, even though the median of <em>all</em> effects is 0.15. This is why <em>post-hoc</em> power-analyses using the observed effect-sizes in your sample are typically not a great idea. Because the choice to run the power analysis is conditioned on the result being significant, you’ve effectively subjected yourself to publication bias, and as a result the power analysis will tend to yield an inflated estimate of power.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by David Baranger.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
